name: Docker

on:
  schedule:
    - cron: '4 2 */30 * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
        - basic11
        python:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
        variant:
        - 'slim'
        - 'slim-bullseye'
        - 'bullseye'
        - 'bookworm'
        poetry:
        - '1.3'
        - '1.7'
    permissions:
      contents: read
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: type=raw,value=${{ matrix.folder }}-py${{ matrix.python }}-${{ matrix.variant }}-po${{ matrix.poetry }}

      - uses: docker/build-push-action@v5
        id: build-and-push
        with:
          context: ${{ matrix.folder }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PYTHON_TAG=${{ matrix.python }}-${{ matrix.variant }}
            POETRY_TAG=${{ matrix.poetry }}.*
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
